# Location.srv
# Request
int32 robot_id
---
# Response
int32 robot_id
int32 location_id

# location_id values:
# id | name
# 0  | LOB_WAITING
# 1  | LOB_CALL
# 2  | RES_PICKUP
# 3  | RES_CALL
# 4  | SUP_PICKUP
# 5  | ELE_1
# 6  | ELE_2
# 101| ROOM_101
# 102| ROOM_102
# 201| ROOM_201
# 202| ROOM_202 