# ButtonStatus.srv
# Request
int32 robot_id
int32[] button_ids
---
# Response
int32 robot_id
bool success
float32[] xs
float32[] ys
float32[] depths
bool[] is_pressed
builtin_interfaces/Time[] timestamp

# button_id values:
# 100: 하행버튼 
# 101: 상행버튼
# 1: 1층
# 2: 2층
# 3: 3층 